/*
 * This file is generated by jOOQ.
 */
package my.mpp.jooq.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import my.mpp.jooq.tables.JCustomers;
import my.mpp.jooq.tables.records.JCustomersRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JCustomersDao extends DAOImpl<JCustomersRecord, my.mpp.jooq.tables.pojos.JCustomers, Integer> {

    /**
     * Create a new JCustomersDao without any configuration
     */
    public JCustomersDao() {
        super(JCustomers.CUSTOMERS, my.mpp.jooq.tables.pojos.JCustomers.class);
    }

    /**
     * Create a new JCustomersDao with an attached configuration
     */
    public JCustomersDao(Configuration configuration) {
        super(JCustomers.CUSTOMERS, my.mpp.jooq.tables.pojos.JCustomers.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(my.mpp.jooq.tables.pojos.JCustomers object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<my.mpp.jooq.tables.pojos.JCustomers> fetchByJId(Integer... values) {
        return fetch(JCustomers.CUSTOMERS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public my.mpp.jooq.tables.pojos.JCustomers fetchOneByJId(Integer value) {
        return fetchOne(JCustomers.CUSTOMERS.ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<my.mpp.jooq.tables.pojos.JCustomers> fetchByJName(String... values) {
        return fetch(JCustomers.CUSTOMERS.NAME, values);
    }
}
