/*
 * This file is generated by jOOQ.
 */
package my.mpp.jooq.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import my.mpp.jooq.tables.JFlywaySchemaHistory;
import my.mpp.jooq.tables.records.JFlywaySchemaHistoryRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JFlywaySchemaHistoryDao extends DAOImpl<JFlywaySchemaHistoryRecord, my.mpp.jooq.tables.pojos.JFlywaySchemaHistory, Integer> {

    /**
     * Create a new JFlywaySchemaHistoryDao without any configuration
     */
    public JFlywaySchemaHistoryDao() {
        super(JFlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, my.mpp.jooq.tables.pojos.JFlywaySchemaHistory.class);
    }

    /**
     * Create a new JFlywaySchemaHistoryDao with an attached configuration
     */
    public JFlywaySchemaHistoryDao(Configuration configuration) {
        super(JFlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, my.mpp.jooq.tables.pojos.JFlywaySchemaHistory.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(my.mpp.jooq.tables.pojos.JFlywaySchemaHistory object) {
        return object.getInstalledRank();
    }

    /**
     * Fetch records that have <code>installed_rank IN (values)</code>
     */
    public List<my.mpp.jooq.tables.pojos.JFlywaySchemaHistory> fetchByJInstalledRank(Integer... values) {
        return fetch(JFlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK, values);
    }

    /**
     * Fetch a unique record that has <code>installed_rank = value</code>
     */
    public my.mpp.jooq.tables.pojos.JFlywaySchemaHistory fetchOneByJInstalledRank(Integer value) {
        return fetchOne(JFlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK, value);
    }

    /**
     * Fetch records that have <code>version IN (values)</code>
     */
    public List<my.mpp.jooq.tables.pojos.JFlywaySchemaHistory> fetchByJVersion(String... values) {
        return fetch(JFlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.VERSION, values);
    }

    /**
     * Fetch records that have <code>description IN (values)</code>
     */
    public List<my.mpp.jooq.tables.pojos.JFlywaySchemaHistory> fetchByJDescription(String... values) {
        return fetch(JFlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.DESCRIPTION, values);
    }

    /**
     * Fetch records that have <code>type IN (values)</code>
     */
    public List<my.mpp.jooq.tables.pojos.JFlywaySchemaHistory> fetchByJType(String... values) {
        return fetch(JFlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.TYPE, values);
    }

    /**
     * Fetch records that have <code>script IN (values)</code>
     */
    public List<my.mpp.jooq.tables.pojos.JFlywaySchemaHistory> fetchByJScript(String... values) {
        return fetch(JFlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SCRIPT, values);
    }

    /**
     * Fetch records that have <code>checksum IN (values)</code>
     */
    public List<my.mpp.jooq.tables.pojos.JFlywaySchemaHistory> fetchByJChecksum(Integer... values) {
        return fetch(JFlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.CHECKSUM, values);
    }

    /**
     * Fetch records that have <code>installed_by IN (values)</code>
     */
    public List<my.mpp.jooq.tables.pojos.JFlywaySchemaHistory> fetchByJInstalledBy(String... values) {
        return fetch(JFlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_BY, values);
    }

    /**
     * Fetch records that have <code>installed_on IN (values)</code>
     */
    public List<my.mpp.jooq.tables.pojos.JFlywaySchemaHistory> fetchByJInstalledOn(Timestamp... values) {
        return fetch(JFlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_ON, values);
    }

    /**
     * Fetch records that have <code>execution_time IN (values)</code>
     */
    public List<my.mpp.jooq.tables.pojos.JFlywaySchemaHistory> fetchByJExecutionTime(Integer... values) {
        return fetch(JFlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.EXECUTION_TIME, values);
    }

    /**
     * Fetch records that have <code>success IN (values)</code>
     */
    public List<my.mpp.jooq.tables.pojos.JFlywaySchemaHistory> fetchByJSuccess(Boolean... values) {
        return fetch(JFlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS, values);
    }
}
