/*
 * This file is generated by jOOQ.
 */
package my.mpp.jooq.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import my.mpp.jooq.tables.JOrders;
import my.mpp.jooq.tables.records.JOrdersRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JOrdersDao extends DAOImpl<JOrdersRecord, my.mpp.jooq.tables.pojos.JOrders, Integer> {

    /**
     * Create a new JOrdersDao without any configuration
     */
    public JOrdersDao() {
        super(JOrders.ORDERS, my.mpp.jooq.tables.pojos.JOrders.class);
    }

    /**
     * Create a new JOrdersDao with an attached configuration
     */
    public JOrdersDao(Configuration configuration) {
        super(JOrders.ORDERS, my.mpp.jooq.tables.pojos.JOrders.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(my.mpp.jooq.tables.pojos.JOrders object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<my.mpp.jooq.tables.pojos.JOrders> fetchByJId(Integer... values) {
        return fetch(JOrders.ORDERS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public my.mpp.jooq.tables.pojos.JOrders fetchOneByJId(Integer value) {
        return fetchOne(JOrders.ORDERS.ID, value);
    }

    /**
     * Fetch records that have <code>product IN (values)</code>
     */
    public List<my.mpp.jooq.tables.pojos.JOrders> fetchByJProduct(String... values) {
        return fetch(JOrders.ORDERS.PRODUCT, values);
    }

    /**
     * Fetch records that have <code>sum IN (values)</code>
     */
    public List<my.mpp.jooq.tables.pojos.JOrders> fetchByJSum(Integer... values) {
        return fetch(JOrders.ORDERS.SUM, values);
    }

    /**
     * Fetch records that have <code>comment IN (values)</code>
     */
    public List<my.mpp.jooq.tables.pojos.JOrders> fetchByJComment(String... values) {
        return fetch(JOrders.ORDERS.COMMENT, values);
    }

    /**
     * Fetch records that have <code>customer IN (values)</code>
     */
    public List<my.mpp.jooq.tables.pojos.JOrders> fetchByJCustomer(String... values) {
        return fetch(JOrders.ORDERS.CUSTOMER, values);
    }
}
