/*
 * This file is generated by jOOQ.
 */
package my.mpp.jooq.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import my.mpp.jooq.tables.JProducts;
import my.mpp.jooq.tables.records.JProductsRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JProductsDao extends DAOImpl<JProductsRecord, my.mpp.jooq.tables.pojos.JProducts, Integer> {

    /**
     * Create a new JProductsDao without any configuration
     */
    public JProductsDao() {
        super(JProducts.PRODUCTS, my.mpp.jooq.tables.pojos.JProducts.class);
    }

    /**
     * Create a new JProductsDao with an attached configuration
     */
    public JProductsDao(Configuration configuration) {
        super(JProducts.PRODUCTS, my.mpp.jooq.tables.pojos.JProducts.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(my.mpp.jooq.tables.pojos.JProducts object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<my.mpp.jooq.tables.pojos.JProducts> fetchByJId(Integer... values) {
        return fetch(JProducts.PRODUCTS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public my.mpp.jooq.tables.pojos.JProducts fetchOneByJId(Integer value) {
        return fetchOne(JProducts.PRODUCTS.ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<my.mpp.jooq.tables.pojos.JProducts> fetchByJName(String... values) {
        return fetch(JProducts.PRODUCTS.NAME, values);
    }
}
