import kotlin.String

/**
 * Generated by [gradle-kotlin-dsl-libs](https://github.com/jmfayard/gradle-kotlin-dsl-libs)
 *
 * Run again
 *   `$ ./gradlew syncLibs`
 * to update this file */
object Libs {
    /**
     * [flyway-core website](https://flywaydb.org) */
    const val flyway_core: String = "org.flywaydb:flyway-core:" + Versions.flyway_core

    /**
     * [google-services website](http://tools.android.com/) */
    const val google_services: String = "com.google.gms:google-services:" + Versions.google_services

    const val gradle_node_plugin: String =
            "com.moowork.gradle:gradle-node-plugin:" + Versions.gradle_node_plugin

    /**
     * [HikariCP website](https://github.com/brettwooldridge/HikariCP) */
    const val hikaricp: String = "com.zaxxer:HikariCP:" + Versions.hikaricp

    /**
     * [gradle website](https://developer.android.com/studio) */
    const val io_fabric_tools_gradle: String =
            "com.android.tools.build:gradle:" + Versions.io_fabric_tools_gradle

    /**
     * [jackson-module-kotlin website](https://github.com/FasterXML/jackson-module-kotlin) */
    const val jackson_module_kotlin: String =
            "com.fasterxml.jackson.module:jackson-module-kotlin:" + Versions.jackson_module_kotlin

    const val jmfayard_github_io_gradle_kotlin_dsl_libs_gradle_plugin: String =
            "jmfayard.github.io.gradle-kotlin-dsl-libs:jmfayard.github.io.gradle-kotlin-dsl-libs.gradle.plugin:" + Versions.jmfayard_github_io_gradle_kotlin_dsl_libs_gradle_plugin

    /**
     * [jooq website](http://www.jooq.org) */
    const val jooq: String = "org.jooq:jooq:" + Versions.jooq

    /**
     * [jooq-codegen website](http://www.jooq.org) */
    const val jooq_codegen: String = "org.jooq:jooq-codegen:" + Versions.jooq_codegen

    /**
     * [kotlin-allopen website](https://kotlinlang.org/) */
    const val kotlin_allopen: String =
            "org.jetbrains.kotlin:kotlin-allopen:" + Versions.kotlin_allopen

    const val kotlin_frontend_plugin: String =
            "org.jetbrains.kotlin:kotlin-frontend-plugin:" + Versions.kotlin_frontend_plugin

    /**
     * [kotlin-gradle-plugin website](https://kotlinlang.org/) */
    const val kotlin_gradle_plugin: String =
            "org.jetbrains.kotlin:kotlin-gradle-plugin:" + Versions.kotlin_gradle_plugin

    const val kotlin_native_gradle_plugin: String =
            "org.jetbrains.kotlin:kotlin-native-gradle-plugin:" + Versions.kotlin_native_gradle_plugin

    const val kotlin_react: String = "org.jetbrains:kotlin-react:" + Versions.kotlin_react

    const val kotlin_react_dom: String =
            "org.jetbrains:kotlin-react-dom:" + Versions.kotlin_react_dom

    const val kotlin_react_router_dom: String =
            "org.jetbrains:kotlin-react-router-dom:" + Versions.kotlin_react_router_dom

    /**
     * [kotlin-scripting-compiler-embeddable website](https://kotlinlang.org/) */
    const val kotlin_scripting_compiler_embeddable: String =
            "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:" + Versions.kotlin_scripting_compiler_embeddable

    /**
     * [kotlin-serialization website](https://kotlinlang.org/) */
    const val kotlin_serialization: String =
            "org.jetbrains.kotlin:kotlin-serialization:" + Versions.kotlin_serialization

    /**
     * [kotlin-serialization-unshaded website](https://kotlinlang.org/) */
    const val kotlin_serialization_unshaded: String =
            "org.jetbrains.kotlin:kotlin-serialization-unshaded:" + Versions.kotlin_serialization_unshaded

    /**
     * [kotlin-stdlib-common website](https://kotlinlang.org/) */
    const val kotlin_stdlib_common: String =
            "org.jetbrains.kotlin:kotlin-stdlib-common:" + Versions.kotlin_stdlib_common

    /**
     * [kotlin-stdlib-js website](https://kotlinlang.org/) */
    const val kotlin_stdlib_js: String =
            "org.jetbrains.kotlin:kotlin-stdlib-js:" + Versions.kotlin_stdlib_js

    /**
     * [kotlin-test website](https://kotlinlang.org/) */
    const val kotlin_test: String = "org.jetbrains.kotlin:kotlin-test:" + Versions.kotlin_test

    /**
     * [kotlin-test-annotations-common website](https://kotlinlang.org/) */
    const val kotlin_test_annotations_common: String =
            "org.jetbrains.kotlin:kotlin-test-annotations-common:" + Versions.kotlin_test_annotations_common

    /**
     * [kotlin-test-common website](https://kotlinlang.org/) */
    const val kotlin_test_common: String =
            "org.jetbrains.kotlin:kotlin-test-common:" + Versions.kotlin_test_common

    /**
     * [kotlin-test-js website](https://kotlinlang.org/) */
    const val kotlin_test_js: String =
            "org.jetbrains.kotlin:kotlin-test-js:" + Versions.kotlin_test_js

    /**
     * [kotlinx-coroutines-core-js website](https://github.com/Kotlin/kotlinx.coroutines) */
    const val kotlinx_coroutines_core_js: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-core-js:" + Versions.kotlinx_coroutines_core_js

    /**
     * [kotlinx-html-js website](https://github.com/Kotlin/kotlinx.html) */
    const val kotlinx_html_js: String =
            "org.jetbrains.kotlinx:kotlinx-html-js:" + Versions.kotlinx_html_js

    /**
     * [kotlinx-serialization-runtime website](https://github.com/Kotlin/kotlinx.serialization) */
    const val kotlinx_serialization_runtime: String =
            "org.jetbrains.kotlinx:kotlinx-serialization-runtime:" + Versions.kotlinx_serialization_runtime

    /**
     * [kotlinx-serialization-runtime-common website](https://github.com/Kotlin/kotlinx.serialization) */
    const val kotlinx_serialization_runtime_common: String =
            "org.jetbrains.kotlinx:kotlinx-serialization-runtime-common:" + Versions.kotlinx_serialization_runtime_common

    /**
     * [kotlinx-serialization-runtime-js website](https://github.com/Kotlin/kotlinx.serialization) */
    const val kotlinx_serialization_runtime_js: String =
            "org.jetbrains.kotlinx:kotlinx-serialization-runtime-js:" + Versions.kotlinx_serialization_runtime_js

    /**
     * [kotlinx-coroutines-core website](https://github.com/Kotlin/kotlinx.coroutines) */
    const val org_jetbrains_kotlinx_kotlinx_coroutines_core: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-core:" + Versions.org_jetbrains_kotlinx_kotlinx_coroutines_core

    /**
     * [postgresql website](https://github.com/pgjdbc/pgjdbc) */
    const val postgresql: String = "org.postgresql:postgresql:" + Versions.postgresql

    const val shadow: String = "com.github.jengelman.gradle.plugins:shadow:" + Versions.shadow

    /**
     * [spring-boot-gradle-plugin website](https://projects.spring.io/spring-boot/#/spring-boot-parent/spring-boot-tools/spring-boot-gradle-plugin) */
    const val spring_boot_gradle_plugin: String =
            "org.springframework.boot:spring-boot-gradle-plugin:" + Versions.spring_boot_gradle_plugin

    /**
     * [spring-boot-starter-jooq website](https://projects.spring.io/spring-boot/#/spring-boot-parent/spring-boot-starters/spring-boot-starter-jooq) */
    const val spring_boot_starter_jooq: String =
            "org.springframework.boot:spring-boot-starter-jooq:" + Versions.spring_boot_starter_jooq

    /**
     * [spring-boot-starter-test website](https://projects.spring.io/spring-boot/#/spring-boot-parent/spring-boot-starters/spring-boot-starter-test) */
    const val spring_boot_starter_test: String =
            "org.springframework.boot:spring-boot-starter-test:" + Versions.spring_boot_starter_test

    /**
     * [spring-boot-starter-web website](https://projects.spring.io/spring-boot/#/spring-boot-parent/spring-boot-starters/spring-boot-starter-web) */
    const val spring_boot_starter_web: String =
            "org.springframework.boot:spring-boot-starter-web:" + Versions.spring_boot_starter_web

    /**
     * [spring-boot-starter-webflux website](https://projects.spring.io/spring-boot/#/spring-boot-parent/spring-boot-starters/spring-boot-starter-webflux) */
    const val spring_boot_starter_webflux: String =
            "org.springframework.boot:spring-boot-starter-webflux:" + Versions.spring_boot_starter_webflux

    object Versions {
        const val flyway_core: String = "5.2.4" // available: milestone=6.0.0-beta

        const val google_services: String = "3.1.1" // available: milestone=4.2.0

        const val gradle_node_plugin: String = "1.2.0" // up-to-date

        const val hikaricp: String = "3.1.0" // available: milestone=3.3.1

        const val io_fabric_tools_gradle: String = "3.1.4" // available: milestone=3.5.0-alpha06

        const val jackson_module_kotlin: String = "2.9.8" // up-to-date

        const val jmfayard_github_io_gradle_kotlin_dsl_libs_gradle_plugin: String =
                "0.2.1" // available: milestone=0.2.6

        const val jooq: String = "3.11.7" // available: milestone=3.11.9

        const val jooq_codegen: String = "3.11.7" // available: milestone=3.11.9

        const val kotlin_allopen: String = "1.3.21" // available: milestone=1.3.40-dev-197

        const val kotlin_frontend_plugin: String = "0.0.37" // available: milestone=0.0.45

        const val kotlin_gradle_plugin: String = "1.3.21" // available: milestone=1.3.40-dev-197

        const val kotlin_native_gradle_plugin: String = "0.8.1" // available: milestone=1.3.21

        const val kotlin_react: String =
                "16.4.2-pre.38-kotlin-1.2.60" // available: milestone=16.6.0-pre.69-kotlin-1.3.21

        const val kotlin_react_dom: String =
                "16.4.2-pre.38-kotlin-1.2.60" // available: milestone=16.6.0-pre.69-kotlin-1.3.21

        const val kotlin_react_router_dom: String =
                "4.3.1-pre.38-kotlin-1.2.60" // available: milestone=4.3.1-pre.69-kotlin-1.3.21

        const val kotlin_scripting_compiler_embeddable: String =
                "1.3.21" // available: milestone=1.3.40-dev-197

        const val kotlin_serialization: String = "1.3.21" // available: milestone=1.3.40-dev-197

        const val kotlin_serialization_unshaded: String =
                "1.3.21" // available: milestone=1.3.40-dev-197

        const val kotlin_stdlib_common: String = "1.3.21" // available: milestone=1.3.40-dev-197

        const val kotlin_stdlib_js: String = "1.3.21" // available: milestone=1.3.40-dev-197

        const val kotlin_test: String = "1.3.21" // available: milestone=1.3.40-dev-197

        const val kotlin_test_annotations_common: String =
                "1.3.21" // available: milestone=1.3.40-dev-197

        const val kotlin_test_common: String = "1.3.21" // available: milestone=1.3.40-dev-197

        const val kotlin_test_js: String = "1.3.21" // available: milestone=1.3.40-dev-197

        const val kotlinx_coroutines_core_js: String = "1.1.1" // up-to-date

        const val kotlinx_html_js: String = "0.6.12" // up-to-date

        const val kotlinx_serialization_runtime: String = "0.10.0" // up-to-date

        const val kotlinx_serialization_runtime_common: String = "0.10.0" // up-to-date

        const val kotlinx_serialization_runtime_js: String = "0.10.0" // up-to-date

        const val org_jetbrains_kotlinx_kotlinx_coroutines_core: String = "1.1.1" // up-to-date

        const val postgresql: String = "42.2.2" // available: milestone=42.2.5

        const val shadow: String = "2.0.1" // available: milestone=5.0.0

        const val spring_boot_gradle_plugin: String =
                "2.2.0.BUILD-SNAPSHOT" // exceed the version found: 2.1.3.RELEASE

        const val spring_boot_starter_jooq: String =
                "2.2.0.BUILD-SNAPSHOT" // exceed the version found: 2.1.3.RELEASE

        const val spring_boot_starter_test: String =
                "2.2.0.BUILD-SNAPSHOT" // exceed the version found: 2.1.3.RELEASE

        const val spring_boot_starter_web: String =
                "2.2.0.BUILD-SNAPSHOT" // exceed the version found: 2.1.3.RELEASE

        const val spring_boot_starter_webflux: String =
                "2.2.0.BUILD-SNAPSHOT" // exceed the version found: 2.1.3.RELEASE
    }

    object Gradle {
        const val runningVersion: String = "4.7"

        const val currentVersion: String = "5.2.1"

        const val nightlyVersion: String = "5.4-20190305000052+0000"

        const val releaseCandidate: String = ""
    }
}
