/*
 * This file is generated by jOOQ.
 */
package my.mpp.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import my.mpp.jooq.Indexes;
import my.mpp.jooq.JPublic;
import my.mpp.jooq.Keys;
import my.mpp.jooq.tables.records.JOrdersRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JOrders extends TableImpl<JOrdersRecord> {

    private static final long serialVersionUID = 1831051128;

    /**
     * The reference instance of <code>public.orders</code>
     */
    public static final JOrders ORDERS = new JOrders();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JOrdersRecord> getRecordType() {
        return JOrdersRecord.class;
    }

    /**
     * The column <code>public.orders.id</code>.
     */
    public final TableField<JOrdersRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('orders_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.orders.product</code>.
     */
    public final TableField<JOrdersRecord, String> PRODUCT = createField("product", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.orders.sum</code>.
     */
    public final TableField<JOrdersRecord, Integer> SUM = createField("sum", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.orders.comment</code>.
     */
    public final TableField<JOrdersRecord, String> COMMENT = createField("comment", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.orders.customer</code>.
     */
    public final TableField<JOrdersRecord, String> CUSTOMER = createField("customer", org.jooq.impl.SQLDataType.VARCHAR.nullable(false).defaultValue(org.jooq.impl.DSL.field("''::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * Create a <code>public.orders</code> table reference
     */
    public JOrders() {
        this(DSL.name("orders"), null);
    }

    /**
     * Create an aliased <code>public.orders</code> table reference
     */
    public JOrders(String alias) {
        this(DSL.name(alias), ORDERS);
    }

    /**
     * Create an aliased <code>public.orders</code> table reference
     */
    public JOrders(Name alias) {
        this(alias, ORDERS);
    }

    private JOrders(Name alias, Table<JOrdersRecord> aliased) {
        this(alias, aliased, null);
    }

    private JOrders(Name alias, Table<JOrdersRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> JOrders(Table<O> child, ForeignKey<O, JOrdersRecord> key) {
        super(child, key, ORDERS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return JPublic.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ORDERS_ID_UINDEX, Indexes.ORDERS_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<JOrdersRecord, Integer> getIdentity() {
        return Keys.IDENTITY_ORDERS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<JOrdersRecord> getPrimaryKey() {
        return Keys.ORDERS_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<JOrdersRecord>> getKeys() {
        return Arrays.<UniqueKey<JOrdersRecord>>asList(Keys.ORDERS_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JOrders as(String alias) {
        return new JOrders(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JOrders as(Name alias) {
        return new JOrders(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public JOrders rename(String name) {
        return new JOrders(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public JOrders rename(Name name) {
        return new JOrders(name, null);
    }
}
