/*
 * This file is generated by jOOQ.
 */
package my.mpp.jooq;


import javax.annotation.Generated;

import my.mpp.jooq.tables.JCustomers;
import my.mpp.jooq.tables.JFlywaySchemaHistory;
import my.mpp.jooq.tables.JOrders;
import my.mpp.jooq.tables.JProducts;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index CUSTOMERS_ID_UINDEX = Indexes0.CUSTOMERS_ID_UINDEX;
    public static final Index CUSTOMERS_PK = Indexes0.CUSTOMERS_PK;
    public static final Index FLYWAY_SCHEMA_HISTORY_PK = Indexes0.FLYWAY_SCHEMA_HISTORY_PK;
    public static final Index FLYWAY_SCHEMA_HISTORY_S_IDX = Indexes0.FLYWAY_SCHEMA_HISTORY_S_IDX;
    public static final Index ORDERS_ID_UINDEX = Indexes0.ORDERS_ID_UINDEX;
    public static final Index ORDERS_PK = Indexes0.ORDERS_PK;
    public static final Index PRODUCTS_ID_UINDEX = Indexes0.PRODUCTS_ID_UINDEX;
    public static final Index PRODUCTS_PK = Indexes0.PRODUCTS_PK;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index CUSTOMERS_ID_UINDEX = Internal.createIndex("customers_id_uindex", JCustomers.CUSTOMERS, new OrderField[] { JCustomers.CUSTOMERS.ID }, true);
        public static Index CUSTOMERS_PK = Internal.createIndex("customers_pk", JCustomers.CUSTOMERS, new OrderField[] { JCustomers.CUSTOMERS.ID }, true);
        public static Index FLYWAY_SCHEMA_HISTORY_PK = Internal.createIndex("flyway_schema_history_pk", JFlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { JFlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
        public static Index FLYWAY_SCHEMA_HISTORY_S_IDX = Internal.createIndex("flyway_schema_history_s_idx", JFlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { JFlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS }, false);
        public static Index ORDERS_ID_UINDEX = Internal.createIndex("orders_id_uindex", JOrders.ORDERS, new OrderField[] { JOrders.ORDERS.ID }, true);
        public static Index ORDERS_PK = Internal.createIndex("orders_pk", JOrders.ORDERS, new OrderField[] { JOrders.ORDERS.ID }, true);
        public static Index PRODUCTS_ID_UINDEX = Internal.createIndex("products_id_uindex", JProducts.PRODUCTS, new OrderField[] { JProducts.PRODUCTS.ID }, true);
        public static Index PRODUCTS_PK = Internal.createIndex("products_pk", JProducts.PRODUCTS, new OrderField[] { JProducts.PRODUCTS.ID }, true);
    }
}
