/*
 * This file is generated by jOOQ.
 */
package my.mpp.jooq;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import my.mpp.jooq.tables.JCustomers;
import my.mpp.jooq.tables.JFlywaySchemaHistory;
import my.mpp.jooq.tables.JOrders;
import my.mpp.jooq.tables.JProducts;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JPublic extends SchemaImpl {

    private static final long serialVersionUID = -1984785439;

    /**
     * The reference instance of <code>public</code>
     */
    public static final JPublic PUBLIC = new JPublic();

    /**
     * The table <code>public.customers</code>.
     */
    public final JCustomers CUSTOMERS = my.mpp.jooq.tables.JCustomers.CUSTOMERS;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public final JFlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = my.mpp.jooq.tables.JFlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.orders</code>.
     */
    public final JOrders ORDERS = my.mpp.jooq.tables.JOrders.ORDERS;

    /**
     * The table <code>public.products</code>.
     */
    public final JProducts PRODUCTS = my.mpp.jooq.tables.JProducts.PRODUCTS;

    /**
     * No further instances allowed
     */
    private JPublic() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.CUSTOMERS_ID_SEQ,
            Sequences.ORDERS_ID_SEQ,
            Sequences.PRODUCTS_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            JCustomers.CUSTOMERS,
            JFlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            JOrders.ORDERS,
            JProducts.PRODUCTS);
    }
}
