/*
 * This file is generated by jOOQ.
 */
package my.mpp.jooq;


import javax.annotation.Generated;

import my.mpp.jooq.tables.JCustomers;
import my.mpp.jooq.tables.JFlywaySchemaHistory;
import my.mpp.jooq.tables.JOrders;
import my.mpp.jooq.tables.JProducts;
import my.mpp.jooq.tables.records.JCustomersRecord;
import my.mpp.jooq.tables.records.JFlywaySchemaHistoryRecord;
import my.mpp.jooq.tables.records.JOrdersRecord;
import my.mpp.jooq.tables.records.JProductsRecord;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<JCustomersRecord, Integer> IDENTITY_CUSTOMERS = Identities0.IDENTITY_CUSTOMERS;
    public static final Identity<JOrdersRecord, Integer> IDENTITY_ORDERS = Identities0.IDENTITY_ORDERS;
    public static final Identity<JProductsRecord, Integer> IDENTITY_PRODUCTS = Identities0.IDENTITY_PRODUCTS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<JCustomersRecord> CUSTOMERS_PK = UniqueKeys0.CUSTOMERS_PK;
    public static final UniqueKey<JFlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = UniqueKeys0.FLYWAY_SCHEMA_HISTORY_PK;
    public static final UniqueKey<JOrdersRecord> ORDERS_PK = UniqueKeys0.ORDERS_PK;
    public static final UniqueKey<JProductsRecord> PRODUCTS_PK = UniqueKeys0.PRODUCTS_PK;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<JCustomersRecord, Integer> IDENTITY_CUSTOMERS = Internal.createIdentity(JCustomers.CUSTOMERS, JCustomers.CUSTOMERS.ID);
        public static Identity<JOrdersRecord, Integer> IDENTITY_ORDERS = Internal.createIdentity(JOrders.ORDERS, JOrders.ORDERS.ID);
        public static Identity<JProductsRecord, Integer> IDENTITY_PRODUCTS = Internal.createIdentity(JProducts.PRODUCTS, JProducts.PRODUCTS.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<JCustomersRecord> CUSTOMERS_PK = Internal.createUniqueKey(JCustomers.CUSTOMERS, "customers_pk", JCustomers.CUSTOMERS.ID);
        public static final UniqueKey<JFlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = Internal.createUniqueKey(JFlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, "flyway_schema_history_pk", JFlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK);
        public static final UniqueKey<JOrdersRecord> ORDERS_PK = Internal.createUniqueKey(JOrders.ORDERS, "orders_pk", JOrders.ORDERS.ID);
        public static final UniqueKey<JProductsRecord> PRODUCTS_PK = Internal.createUniqueKey(JProducts.PRODUCTS, "products_pk", JProducts.PRODUCTS.ID);
    }
}
