/*
 * This file is generated by jOOQ.
 */
package my.mpp.jooq;


import javax.annotation.Generated;

import my.mpp.jooq.tables.JCustomers;
import my.mpp.jooq.tables.JFlywaySchemaHistory;
import my.mpp.jooq.tables.JOrders;
import my.mpp.jooq.tables.JProducts;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.customers</code>.
     */
    public static final JCustomers CUSTOMERS = my.mpp.jooq.tables.JCustomers.CUSTOMERS;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final JFlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = my.mpp.jooq.tables.JFlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.orders</code>.
     */
    public static final JOrders ORDERS = my.mpp.jooq.tables.JOrders.ORDERS;

    /**
     * The table <code>public.products</code>.
     */
    public static final JProducts PRODUCTS = my.mpp.jooq.tables.JProducts.PRODUCTS;
}
