/*
 * This file is generated by jOOQ.
 */
package my.mpp.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JOrders implements Serializable {

    private static final long serialVersionUID = -171317703;

    private Integer id;
    private String  product;
    private Integer sum;
    private String  comment;
    private String  customer;

    public JOrders() {}

    public JOrders(JOrders value) {
        this.id = value.id;
        this.product = value.product;
        this.sum = value.sum;
        this.comment = value.comment;
        this.customer = value.customer;
    }

    public JOrders(
        Integer id,
        String  product,
        Integer sum,
        String  comment,
        String  customer
    ) {
        this.id = id;
        this.product = product;
        this.sum = sum;
        this.comment = comment;
        this.customer = customer;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getProduct() {
        return this.product;
    }

    public void setProduct(String product) {
        this.product = product;
    }

    public Integer getSum() {
        return this.sum;
    }

    public void setSum(Integer sum) {
        this.sum = sum;
    }

    public String getComment() {
        return this.comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public String getCustomer() {
        return this.customer;
    }

    public void setCustomer(String customer) {
        this.customer = customer;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("JOrders (");

        sb.append(id);
        sb.append(", ").append(product);
        sb.append(", ").append(sum);
        sb.append(", ").append(comment);
        sb.append(", ").append(customer);

        sb.append(")");
        return sb.toString();
    }
}
